# Generated by Django 4.2.17 on 2025-01-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
